spring.profiles.active=dev
spring.application.name=banking
spring.config.import=optional:file:.env[.properties]

open.api.title=Bank App API
open.api.description=Backend REST APIs for Banking System
open.api.version=v1.0.0